// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu1wXFduiC0-3GmJp5T4QA1b5Mcp4liXg',
    appId: '1:432431197181:web:3f3fadea4046b41904c794',
    messagingSenderId: '432431197181',
    projectId: 'kahoot-b61b0',
    authDomain: 'kahoot-b61b0.firebaseapp.com',
    storageBucket: 'kahoot-b61b0.firebasestorage.app',
    measurementId: 'G-ESMVFS99JJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2I_zrrNwV2oiL-wB2R990F_GOS-BJnKo',
    appId: '1:432431197181:android:27aef90efac79ab204c794',
    messagingSenderId: '432431197181',
    projectId: 'kahoot-b61b0',
    storageBucket: 'kahoot-b61b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDoSaKnDioF41ptBfUmdvQDqPYyLKpPbc',
    appId: '1:432431197181:ios:edb2e24357f7e57804c794',
    messagingSenderId: '432431197181',
    projectId: 'kahoot-b61b0',
    storageBucket: 'kahoot-b61b0.firebasestorage.app',
    iosBundleId: 'com.example.kahootApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDoSaKnDioF41ptBfUmdvQDqPYyLKpPbc',
    appId: '1:432431197181:ios:edb2e24357f7e57804c794',
    messagingSenderId: '432431197181',
    projectId: 'kahoot-b61b0',
    storageBucket: 'kahoot-b61b0.firebasestorage.app',
    iosBundleId: 'com.example.kahootApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu1wXFduiC0-3GmJp5T4QA1b5Mcp4liXg',
    appId: '1:432431197181:web:ec158124bdc3744304c794',
    messagingSenderId: '432431197181',
    projectId: 'kahoot-b61b0',
    authDomain: 'kahoot-b61b0.firebaseapp.com',
    storageBucket: 'kahoot-b61b0.firebasestorage.app',
    measurementId: 'G-0PVZQ1L9NT',
  );
}
